### ISSUE TITLE
Review updates made on Anvil 16.11.07

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql_spec#2]
We need to update the spec with the following information:
 * information on provenance, place of service, and provider (specialty) filter
 * add provenance filter short cuts
 * talk about using at_least parameters in other temporal operators
 * talk about deprecating certain operators (and talk about removing some operators if not already done so)

Tagging @aguynamedryan for comment and updates.

**Comment by aguynamedryan** [comment]
Done as part of #4
