### ISSUE TITLE
Add details about date adjustments

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql_spec#3]
Stuff like:
- dwmy
- -d-w
- ddd

**Comment by aguynamedryan** [comment]
@markdanese, is this sufficient: https://github.com/outcomesinsights/conceptql_spec#time_window

**Comment by markdanese** [comment]
I think so.  @claire-oi , for the UI, I would like to enforce that a number be present for clarity in the study spec (even though conceptql is smart enough to take a guess).  see #476 (jigsaw diagram editor) for the origin of the question.

One clarification:
10d3m => 3 months and 10 days
-2y10m-3d => -2 years, +10 months, -3 days

Does the above mean that the final date is 10 days + 3 months in the first example, and -2years +10 months - 3 days in the second?  You used commas in one example and "and" in the other, and I just wanted to be sure.  I thought the mathematical operators might be more precise.
